name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Lint
      uses: github/super-linter@v5
      env:
        VALIDATE_MARKDOWN: true
        DEFAULT_WORKSPACE: ${{ github.workspace }}
